//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMNts.EMUService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMNts.EMUService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;tr height=&quot;15&quot;&gt;
        ///			&lt;td style=&quot;font-size:14px;&quot;&gt;#YEAR#&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#DEMU0# kW&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#NEMU0# kW&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#DEMU1# kW&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#NEMU1# kW&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#DEMU2# kW&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#NEMU2# kW&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#DEMU3# kW&lt;/td&gt;
        ///			&lt;td style=&quot;font-size:14px&quot;&gt;#NEMU3# kW&lt;/td&gt;
        ///            &lt;td style=&quot;font-size:14px&quot;&gt;#TOTAL# kW&lt;/td&gt;
        ///		&lt;/tr&gt;.
        /// </summary>
        internal static string AdditionalYears {
            get {
                return ResourceManager.GetString("AdditionalYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EMU_Logo {
            get {
                object obj = ResourceManager.GetObject("EMU_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe&quot; &quot;C:\Program Files\EMU Monitor\EMUService.exe&quot;.
        /// </summary>
        internal static string install_run_as_admin {
            get {
                return ResourceManager.GetString("install_run_as_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html&gt;
        ///	&lt;div style=&quot;font-size:14px&quot;&gt;Hello,&lt;/div&gt;
        ///	&lt;div style=&quot;font-size:14px&quot;&gt;Here are your daily energy usage statistics brought to you by our herd of OptoEMU22&apos;s.&lt;/div&gt;
        ///	&lt;br/&gt;
        ///    &lt;table style=&quot;border-collapse:collapse; text-align:center; font-family:arial; font-size:12px&quot; border=&quot;1&quot; cellpadding=&quot;5&quot; width=&quot;600&quot;&gt;
        ///		&lt;caption style=&quot;font-size:24px&quot;&gt;&lt;em&gt;Energy Use for #DAY#&lt;/em&gt;&lt;/caption&gt;
        ///		&lt;col width=&quot;100&quot;/&gt;
        ///		&lt;col width=&quot;100&quot;/&gt;
        ///		&lt;col width=&quot;200&quot;/&gt;
        ///		#PREVCOLWIDTHS#
        ///		
        ///		&lt;tr heig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainEMail {
            get {
                return ResourceManager.GetString("MainEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;EMU&gt;
        ///	&lt;Setting Name=&quot;VizURL&quot;&gt;http://lmnergy/emu/index.html&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;4WIP&quot;&gt;0.0.0.000&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;4EIP&quot;&gt;0.0.0.001&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;5WIP&quot;&gt;0.0.0.002&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;5EIP&quot;&gt;0.0.0.003&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;Unsubscribe&quot;&gt;admin@MyCompany.com&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;DBServer&quot;&gt;DatabaseServerName&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;DBName&quot;&gt;DatabaseName&lt;/Setting&gt;
        ///	&lt;Setting Name=&quot;DBTableName&quot;&gt;dbo.TableName&lt;/Setting&gt;
        ///	&lt;Setting  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe&quot; /u &quot;C:\Program Files\EMU Monitor\EMUService.exe&quot;.
        /// </summary>
        internal static string uninstall_run_as_admin {
            get {
                return ResourceManager.GetString("uninstall_run_as_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YAxis {
            get {
                object obj = ResourceManager.GetObject("YAxis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
